project_id = "fjyztcfzntlbqgqjefel"

 [functions.aadhaar-lookup]
 verify_jwt = false
 
[functions.number-lookup]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.update-payment-settings]
verify_jwt = false

[functions.get-payment-settings]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false

[functions.check-expired-orders]
verify_jwt = false

[functions.apply-referral]
verify_jwt = false